"""recruiter job added

Revision ID: b185c999502e
Revises: 8946f389beff
Create Date: 2022-01-03 00:30:25.555476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b185c999502e'
down_revision = '8946f389beff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
