"""create success

Revision ID: efeb2dd0efdd
Revises: b185c999502e
Create Date: 2022-01-07 22:49:56.983659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efeb2dd0efdd'
down_revision = 'b185c999502e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seekers', sa.Column('experience_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seekers', 'experience_level')
    # ### end Alembic commands ###
